package dao;// default package
// Generated Mar 20, 2021, 2:25:48 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category"
        , catalog = "biddingschema"
)
public class Category implements java.io.Serializable {


    private int id;
    private String value;
    private String description;
    private Set<Product> products = new HashSet<Product>(0);

    public Category() {
        value = "test";
        description = "test";
    }


    public Category(int id, String value) {
        this.id = id;
        this.value = value;
    }

    public Category(int id, String value, String description, Set<Product> products) {
        this.id = id;
        this.value = value;
        this.description = description;
        this.products = products;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)


    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }


    @Column(name = "value", nullable = false, length = 45)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }


    @Column(name = "description", length = 150)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "product_has_category", catalog = "biddingschema", joinColumns = {
            @JoinColumn(name = "category_id", nullable = false, updatable = false)}, inverseJoinColumns = {
            @JoinColumn(name = "product_id", nullable = false, updatable = false)})
    public Set<Product> getProducts() {
        return this.products;
    }

    public void setProducts(Set<Product> products) {
        this.products = products;
    }


}


