GET http://localhost:9090/REST-D2/api/employee HTTP/1.1
Accept: application/json
###

GET http://localhost:9090/REST-D2/api/employee HTTP/1.1
Accept: application/xml
###

GET http://localhost:9090/REST-D2/api/employee/3 HTTP/1.1
Accept: application/json
###

DELETE  http://localhost:9090/REST-D1/api/employee/30 HTTP/1.1
Accept: application/json
###

POST http://localhost:9090/REST-D1/api/employee HTTP/1.1
Accept: application/json
# Content-Type: application/json

testUpdate2


###
PUT http://localhost:9090/REST-D1/api/employee/3 HTTP/1.1
Accept: application/json

test4

###
PUT http://localhost:9090/REST-D1/api/employee HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "firstName": "test4",
  "id": 3
}

###

POST http://localhost:9090/SOAP-D1/ws/EmployeeService HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://jets.iti.gov.eg/">
    
    <soap:Body>
        <jets:updateEmployee>
            <id>3</id>
            <name>test1</name>
        </jets:updateEmployee>
    </soap:Body>

</soap:Envelope>

###

POST http://localhost:9090/SOAP-D1/ws/EmployeeService HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://jets.iti.gov.eg/">
    
    <soap:Body>
        <jets:deleteEmployee>
            <id>2</id>
        </jets:deleteEmployee>
    </soap:Body>

</soap:Envelope>

###

# ERROR -> what is even "jets" prefix mean !?
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <jets:add>
            <arg0>33</arg0>
            <arg1>33</arg1>
        </jets:add>
    </soap:Body>

</soap:Envelope>

###
# ERROR -> No way to find out where is this add method
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    
    <soap:Body>
        <add>
            <arg0>33</arg0>
            <arg1>33</arg1>
        </add>
    </soap:Body>

</soap:Envelope>





###
# SOAP Fault - Division by zero (Runtime Exception)
POST http://localhost:9595/SOAP-D1/ws/calculator HTTP/1.1
Content-Type: text/xml

<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:jets="http://jets.iti.gov.eg/">
    
    <soap:Body>
        <jets:div>
            <arg0>12</arg0>
            <arg1>0</arg1>
        </jets:div>
    </soap:Body>

</soap:Envelope>
