
package sei;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "EmployeeServiceImpl", targetNamespace = "http://jets.iti.gov.eg/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceImpl {


    /**
     * 
     * @param name
     * @return
     *     returns sei.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addEmployee", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.AddEmployee")
    @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.AddEmployeeResponse")
    @Action(input = "http://jets.iti.gov.eg/EmployeeServiceImpl/addEmployeeRequest", output = "http://jets.iti.gov.eg/EmployeeServiceImpl/addEmployeeResponse")
    public Employee addEmployee(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param name
     * @param id
     * @return
     *     returns sei.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.UpdateEmployeeResponse")
    @Action(input = "http://jets.iti.gov.eg/EmployeeServiceImpl/updateEmployeeRequest", output = "http://jets.iti.gov.eg/EmployeeServiceImpl/updateEmployeeResponse")
    public Employee updateEmployee(
        @WebParam(name = "id", targetNamespace = "")
        int id,
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param id
     * @return
     *     returns sei.Employee
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.GetEmployeeResponse")
    @Action(input = "http://jets.iti.gov.eg/EmployeeServiceImpl/getEmployeeRequest", output = "http://jets.iti.gov.eg/EmployeeServiceImpl/getEmployeeResponse")
    public Employee getEmployee(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteEmployee", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.DeleteEmployee")
    @ResponseWrapper(localName = "deleteEmployeeResponse", targetNamespace = "http://jets.iti.gov.eg/", className = "sei.DeleteEmployeeResponse")
    @Action(input = "http://jets.iti.gov.eg/EmployeeServiceImpl/deleteEmployeeRequest", output = "http://jets.iti.gov.eg/EmployeeServiceImpl/deleteEmployeeResponse")
    public boolean deleteEmployee(
        @WebParam(name = "id", targetNamespace = "")
        int id);

}
